### ISSUE TITLE
Does selenium-grid supports to send extra customised commands from hub to node before starting tests

### ISSUE THREAD

**Issue by pm-ankur-prava** [RationaleEmotions/gridopadesham#2]
Is there any provision in selenium-grid so that we can send / fire some extra commands before starting tests on nodes?
I want to set some settings on mobile device before starting tests from that node.

**Comment by krmahadevan** [comment]
No. I dont think you can do this because unless and until a new session request is fired by the test case (when you instantiate `RemoteWebDriver`) the hub doesn't really know to which node is the test going to be routed to. So this can't be done at the test case level.
But you should be able to do this by building your own custom `RemoteProxy` and then adding your customised logic in its new session request handling piece by doing the following:

1. Build a new servlet which can be added at the node.
2. Have the node servlet do the customisation that is required
3. Build your own custom `RemoteProxy` which would basically invoke your servlet as part of honouring the new session
4. Start your hub using the custom proxy and start your node using the newly added custom servlet.

For a sample servlet refer [GhostProxy](https://github.com/RationaleEmotions/just-ask/blob/master/src/main/java/com/rationaleemotions/proxy/GhostProxy.java)

Again, all of this is in Grid3. The Grid4 architecture has changed and a lot of these things would perhaps not even be applicable on grid4
